-- CreateEnum
CREATE TYPE "Role" AS ENUM ('CLIENT', 'OPMANAGER', 'WHMANAGER', 'SCMANAGER', 'SALMANAGER', 'ADMIN', 'SUPPORT');

-- AlterTable
ALTER TABLE "user" ADD COLUMN     "role" "Role" NOT NULL DEFAULT 'CLIENT';
